# Generated by Django 2.2.1 on 2019-09-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='人物/組織名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='概要')),
            ],
            options={
                'db_table': 'PayFor',
            },
        ),
        migrations.CreateModel(
            name='PayItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(blank=True, null=True, verbose_name='金額')),
                ('rate', models.FloatField(default=0.0, verbose_name='利率（年）')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='期日')),
                ('payfor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money_easy.PayFor', verbose_name='支払先')),
            ],
            options={
                'db_table': 'PayItem',
            },
        ),
    ]
