# Generated by Django 2.2.1 on 2019-10-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_easy', '0004_auto_20191003_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payitem',
            name='duedate',
            field=models.DateField(blank=True, null=True, verbose_name='優先度'),
        ),
    ]
