# Generated by Django 2.2.1 on 2019-10-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_easy', '0005_auto_20191003_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payitem',
            name='duedate',
            field=models.DateField(blank=True, null=True, verbose_name='期日'),
        ),
        migrations.AlterField(
            model_name='payitem',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('info', 'normal'), ('success', 'low')], default='normal', max_length=50, verbose_name='優先度'),
        ),
    ]
